### ISSUE TITLE
SSH key configuration does not take effect

### ISSUE THREAD

**Issue by gitlawr** [rancher/harvester-ui#214]
**Version**
master 11/17

**Steps to reproduce**
1. Create an ssh key
2. Create a VM and select the ssh key
3. Failed to log in with the ssh key

**Other details**
The VM yaml is :
```
      volumes:
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            # some other stuff...
            sshAuthorizedKeys:
              - >-
                ssh-rsa
                AAAAB3NzaC1yc2EAAAADAQABAAABAQCmAZFWNfXPfzV2o203bW1107LpQeynoQ4JhByXRDM3rd1gHW60Xdcbpr7Yi9JHiqSR7YIW+mMpmjacr9bwQ1EjkfsozxHrx69IFfvYRpasBaXdBdHD/Ye3DZ28rQvEEZbyWsa9bIWcWb/m/PPmb2I4p2gX7dGxFxR/DCwUyNk95pra+w5z2H7IyXMHwTI+60dV+GguHaWfCwA/LUnDsq253hJsmAvn4Sr3G2hXqO0x+bD7hWwJHYHi6z1ZU62W3ex7w6D/0+YNh1AhTCkBI9gSKOqnWbkAekbvItSKVVqN9IfkXvvZBsgKPKjledhAHnAvXjt/+Pfkq3RhSEZp7+iL
```

The expected key should be `ssh_authorized_keys` instead of `sshAuthorizedKeys`.
ref: https://cloudinit.readthedocs.io/en/latest/topics/examples.html
