### ISSUE TITLE
add annotations

### ISSUE THREAD

**Issue by WuJun2016** [rancher/harvester-ui#223]
```
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: static
        address: 10.10.1.110/24
        gateway: 10.10.1.0
```
Add ```networks.harvester.cattle.io/ips: [“10.10.1.22/24”] ``` to annotation when there is an address
